"""New Migration

Revision ID: e23151aa8aa9
Revises: 559f0d11d1a0
Create Date: 2021-09-02 12:28:15.118629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23151aa8aa9'
down_revision = '559f0d11d1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
